SELECT * FROM dbo.KHACHHANG,(SELECT * FROM dbo.NHACUNGCAP) AS NCC

SELECT * FROM dbo.KHACHHANG, dbo.NHACUNGCAP

SELECT * FROM dbo.KHACHHANG 
WHERE TENCONGTI LIKE 'ban%%' ESCAPE '%'

SELECT TENCONGTI, COUNT(*)
FROM dbo.KHACHHANG
GROUP BY TENCONGTI

---
CREATE VIEW 

SELECT * INTO demo9
FROM dbo.KHACHHANG, dbo.DONDATHANG
WHERE DONDATHANG.MAKHACHHANG = KHACHHANG.MAKHACHHANG

SELECT * INTO demo 
FROM dbo.KHACHHANG, dbo.DONDATHANG

SELECT * FROM demo

TRUNCATE TABLE demo
INSERT Demo
SELECT KHACHHANG.MAKHACHHANG, TENCONGTI,TENGIAODICH, NGAYGIAOHANG,NGAYCHUYENHANG,NOICHUYENHANG
FROM dbo.KHACHHANG, dbo.DONDATHANG
WHERE DONDATHANG.MAKHACHHANG = KHACHHANG.MAKHACHHANG

TRUNCATE TABLE demo

DROP TABLE demo

SELECT *  FROM demo